version: '3'
services:
  phpunit:
    image: bestitdocker/dps-phpfpm
    links:
      - oxiddb
    volumes:
      - .:/app
    working_dir: /app
    environment:
      TRAVIS_ERROR_LEVEL: 255
  oxiddb:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: oxidehop_ce
      MYSQL_ROOT_PASSWORD: dbpass
